image:
  repository: localhost:5000/gitea/gitea
  tag: 1.15.3
  pullPolicy: IfNotPresent
service:
  ssh:
    type: NodePort
    port: 22
ingress:
  enabled: false
  # className: nginx
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - git.example.com
persistence:
  enabled: true
  size: 8Gi
  storageClass: standard
gitea:
  admin:
    existingSecret: gitea-admin-secret
    email: "ben.wangz@foxmail.com"
  database:
    builtIn:
      postgresql:
        enabled: true
      mysql:
        enabled: false
      mariadb:
        enabled: false
  cache:
    builtIn:
      enabled: true
memcached:
  image:
    registry: docker.io
    repository: localhost:5000/bitnami/memcached
    tag: 1.6.9-debian-10-r114
    pullPolicy: IfNotPresent
  service:
    port: 11211
  persistence:
    enabled: false
  metrics:
    image:
      registry: docker.io
      repository: localhost:5000/bitnami/memcached-exporter
      tag: 0.8.0-debian-10-r105
      pullPolicy: IfNotPresent
postgresql:
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  image:
    registry: docker.io
    repository: localhost:5000/bitnami/postgresql
    tag: 11.11.0-debian-10-r62
    pullPolicy: IfNotPresent
  persistence:
    size: 10Gi
    storageClass: standard
  volumePermissions:
    image:
      registry: docker.io
      repository: localhost:5000/bitnami/bitnami-shell
      tag: "10"
      pullPolicy: IfNotPresent
  metrics:
    image:
      registry: docker.io
      repository: localhost:5000/bitnami/postgres-exporter
      tag: 0.9.0-debian-10-r34
      pullPolicy: IfNotPresent
