image:
  registry: localhost:5000/docker.io
  repository: bitnami/nginx
  tag: 1.21.3-debian-10-r29
  pullPolicy: IfNotPresent
  pullSecrets: [ ]
service:
  type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: self-signed-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hostname: self-signed.nginx.local
  path: /my-nginx-prefix/?(.*)
  tls: true